# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZJP0RB5W5agMoSrvOKEELe4oej0fxOV
"""

# 1. IMPORT LIBRARIES
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# 2. LOAD DATA
data = pd.read_csv("fake_news.csv")

# Convert REAL/FAKE into numbers
data['label'] = data['label'].map({'REAL': 1, 'FAKE': 0})

# 3. SEPARATE TEXT AND LABELS
X = data['text']
y = data['label']

# 4. TRAIN–TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1, stratify=y
)

# 5. TF-IDF
tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=3000,
    min_df=2,
    ngram_range=(1, 2)
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

# 6. TRAIN MODEL
model = LogisticRegression(max_iter=2000, C=0.3)
model.fit(X_train_tfidf, y_train)

# 7. EVALUATION
pred = model.predict(X_test_tfidf)
print("Accuracy:", accuracy_score(y_test, pred))


# 8. PREDICTION FUNCTION
def predict_news(text):
    text_tfidf = tfidf.transform([text])
    prediction = model.predict(text_tfidf)[0]
    return "REAL" if prediction == 1 else "FAKE"

# TEST PREDICTION
news = input("Enter a news article: ")
print(predict_news(news))

